--[[
██████╗ ███████╗██████╗ 
██╔══██╗██╔════╝██╔══██╗
██████╔╝█████╗  ██████╔╝
██╔══██╗██╔══╝  ██╔══██╗
██████╔╝███████╗██║  ██║
╚═════╝ ╚══════╝╚═╝  ╚═╝
DISCORD: ber#8813
--------------------------------------------------------------------------------------------------------------------------------]]
secondInv = {
    ["trash"] = {["icon"] = "drop", ["title"] = "Itens no Chão", ["capacity"] = false},
    ["shop"] = {["icon"] = "shop", ["title"] = "Loja de Itens", ["capacity"] = false},
    ["trunk"] = {["icon"] = "box", ["title"] = "Porta-Malas", ["capacity"] = true},
    ["chest"] = {["icon"] = "box", ["title"] = "Baú", ["capacity"] = true},
}
boxProperty = {
    ["trade_send"] = {
        ["title"] = "Enviar Proposta",
        ["amountchange"] = true,
        ["valuechange"] = true,
        ["value"] = true,
        ["reset"] = true,
        ["multiply"] = true,
        ["max"] = true,
        ["button"] = "ENVIAR",
    },
    ["trade_receive"] = {
        ["title"] = "Proposta Recebida",
        ["amountchange"] = false,
        ["valuechange"] = false,
        ["value"] = true,
        ["reset"] = false,
        ["multiply"] = false,
        ["max"] = false,
        ["button"] = "ACEITAR",
    },
    ["drop_put"] = {
        ["title"] = "Dropar Item",
        ["amountchange"] = true,
        ["valuechange"] = false,
        ["value"] = false,
        ["reset"] = true,
        ["multiply"] = false,
        ["max"] = true,
        ["button"] = "DROPAR",
    },
    ["drop_pick"] = {
        ["title"] = "Pegar Item",
        ["amountchange"] = true,
        ["valuechange"] = false,
        ["value"] = false,
        ["reset"] = true,
        ["multiply"] = false,
        ["max"] = true,
        ["button"] = "PEGAR",
    },
    ["trunk_put"] = {
        ["title"] = "Guardar Item",
        ["amountchange"] = true,
        ["valuechange"] = false,
        ["value"] = false,
        ["reset"] = true,
        ["multiply"] = false,
        ["max"] = true,
        ["button"] = "GUARDAR",
    },
    ["trunk_pick"] = {
        ["title"] = "Pegar Item",
        ["amountchange"] = true,
        ["valuechange"] = false,
        ["value"] = false,
        ["reset"] = true,
        ["multiply"] = false,
        ["max"] = true,
        ["button"] = "PEGAR",
    },
    ["chest_put"] = {
        ["title"] = "Guardar Item",
        ["amountchange"] = true,
        ["valuechange"] = false,
        ["value"] = false,
        ["reset"] = true,
        ["multiply"] = false,
        ["max"] = true,
        ["button"] = "GUARDAR",
    },
    ["chest_pick"] = {
        ["title"] = "Pegar Item",
        ["amountchange"] = true,
        ["valuechange"] = false,
        ["value"] = false,
        ["reset"] = true,
        ["multiply"] = false,
        ["max"] = true,
        ["button"] = "PEGAR",
    },
    ["shop"] = {
        ["title"] = "Adquirir Item",
        ["amountchange"] = true,
        ["valuechange"] = false,
        ["value"] = true,
        ["reset"] = true,
        ["multiply"] = false,
        ["max"] = false,
        ["button"] = "COMPRAR",
    },
}
shops = {
    [1] = {--burguershot LS
        ["name"] = "Lanchonete",
        ["position"] = {377.404, -67.76, 1001.515, 10, 1},
        ["blip"] = false,
        ["items"] = {
            {"burrito", 30, 150},
            {"cafe", 200, 30},
            {"energetico", 1500, 10},
            {"hamburguer", 50, 150},
            {"pizza", 40, 150},
            {"refrigerante", 40, 150},
            {"suco", 30, 150},
        },
    },
    [2] = {--cluckin bell LS
        ["name"] = "Lanchonete",
        ["position"] = {369.705, -6.017, 1001.859, 9, 1},
        ["blip"] = false,
        ["items"] = {
            {"burrito", 30, 150},
            {"cafe", 200, 30},
            {"energetico", 1500, 10},
            {"hamburguer", 50, 150},
            {"pizza", 40, 150},
            {"refrigerante", 40, 150},
            {"suco", 30, 150},
        },
    },
    [3] = {--burguershot LV
        ["name"] = "Lanchonete",
        ["position"] = {377.461, -67.435, 1001.508, 10, 2},
        ["blip"] = false,
        ["items"] = {
            {"burrito", 30, 150},
            {"cafe", 200, 30},
            {"energetico", 1500, 10},
            {"hamburguer", 50, 150},
            {"pizza", 40, 150},
            {"refrigerante", 40, 150},
            {"suco", 30, 150},
        },
    },
    [4] = {--burguershot SF
        ["name"] = "Lanchonete",
        ["position"] = {377.461, -67.435, 1001.508, 10, 3},
        ["blip"] = false,
        ["items"] = {
            {"burrito", 30, 150},
            {"cafe", 200, 30},
            {"energetico", 1500, 10},
            {"hamburguer", 50, 150},
            {"pizza", 40, 150},
            {"refrigerante", 40, 150},
            {"suco", 30, 150},
        },
    },
    [5] = {--24/7 LESTE LS
        ["name"] = "Utilitários",
        ["position"] = {-28.161, -89.954, 1003.547, 18, 1},
        ["blip"] = false,
        ["items"] = {
            {"bandagem", 1000, 40},
            {"capacete", 500, 75},
            {"celular", 1500, 30},
            {"cutelo", 100, 150},
            {"dado", 10, 150},
            {"dildo", 100, 150},
            {"analgesico", 300, 75},
            {"facao", 2500, 20},
            {"garrafa", 10, 300},
            {"gasolina", 5000, 10},
            {"jbl", 5000, 10},
            {"kit_reparo", 5000, 10},
            {"mascara", 500, 50},
            {"maquininha", 5000, 10},
            {"mochila_p", 500, 50},
            {"mochila_m", 2000, 25},
            {"mochila_g", 5000, 10},
            {"moeda", 10, 150},
            {"paraquedas", 3000, 15},
            {"peneira", 100, 150},
            {"picareta", 100, 150},
            {"camisinha", 10, 150},
            {"radinho", 1500, 30},
            {"tesoura", 100, 150},
            {"vaso", 100, 300},
        },
    },
    [6] = {--24/7 NORTE LS
        ["name"] = "Utilitários",
        ["position"] = {-28.161, -89.954, 1003.547, 18, 2},
        ["blip"] = false,
        ["items"] = {
            {"bandagem", 1000, 40},
            {"capacete", 500, 75},
            {"celular", 1500, 30},
            {"cutelo", 100, 150},
            {"dado", 10, 150},
            {"dildo", 100, 150},
            {"analgesico", 300, 75},
            {"facao", 2500, 20},
            {"garrafa", 10, 300},
            {"gasolina", 5000, 10},
            {"jbl", 5000, 10},
            {"kit_reparo", 5000, 10},
            {"mascara", 500, 50},
            {"maquininha", 5000, 10},
            {"mochila_p", 500, 50},
            {"mochila_m", 2000, 25},
            {"mochila_g", 5000, 10},
            {"moeda", 10, 150},
            {"paraquedas", 3000, 15},
            {"peneira", 100, 150},
            {"picareta", 100, 150},
            {"camisinha", 10, 150},
            {"radinho", 1500, 30},
            {"tesoura", 100, 150},
            {"vaso", 100, 300},
        },
    },
    [7] = {--24/7 LV
        ["name"] = "Utilitários",
        ["position"] = {-28.161, -89.954, 1003.547, 18, 3},
        ["blip"] = false,
        ["items"] = {
            {"bandagem", 1000, 40},
            {"capacete", 500, 75},
            {"celular", 1500, 30},
            {"cutelo", 100, 150},
            {"dado", 10, 150},
            {"dildo", 100, 150},
            {"analgesico", 300, 75},
            {"facao", 2500, 20},
            {"garrafa", 10, 300},
            {"gasolina", 5000, 10},
            {"jbl", 5000, 10},
            {"kit_reparo", 5000, 10},
            {"mascara", 500, 50},
            {"maquininha", 5000, 10},
            {"mochila_p", 500, 50},
            {"mochila_m", 2000, 25},
            {"mochila_g", 5000, 10},
            {"moeda", 10, 150},
            {"paraquedas", 3000, 15},
            {"peneira", 100, 150},
            {"picareta", 100, 150},
            {"camisinha", 10, 150},
            {"radinho", 1500, 30},
            {"tesoura", 100, 150},
            {"vaso", 100, 300},
        },
    },
    [8] = {--24/7 SF
        ["name"] = "Utilitários",
        ["position"] = {-28.161, -89.954, 1003.547, 18, 4},
        ["blip"] = false,
        ["items"] = {
            {"bandagem", 1000, 40},
            {"capacete", 500, 75},
            {"celular", 1500, 30},
            {"cutelo", 100, 150},
            {"dado", 10, 150},
            {"dildo", 100, 150},
            {"analgesico", 300, 75},
            {"facao", 2500, 20},
            {"garrafa", 10, 300},
            {"gasolina", 5000, 10},
            {"jbl", 5000, 10},
            {"kit_reparo", 5000, 10},
            {"mascara", 500, 50},
            {"maquininha", 5000, 10},
            {"mochila_p", 500, 50},
            {"mochila_m", 2000, 25},
            {"mochila_g", 5000, 10},
            {"moeda", 10, 150},
            {"paraquedas", 3000, 15},
            {"peneira", 100, 150},
            {"picareta", 100, 150},
            {"camisinha", 10, 150},
            {"radinho", 1500, 30},
            {"tesoura", 100, 150},
            {"vaso", 100, 300},
        },
    },
    [9] = {--BAR PIER LS
        ["name"] = "Bar",
        ["position"] = {359.328, -2031.924, 7.836, 0, 0},
        ["blip"] = 49,
        ["items"] = {
            {"cigarro", 15, 300},
            {"isqueiro", 300, 75},
            {"whisky", 50, 150},
        },
    },
    [10] = {--BAR CJ LS
        ["name"] = "Bar",
        ["position"] = {497.056, -76.041, 998.758, 11, 1},
        ["blip"] = false,
        ["items"] = {
            {"cigarro", 15, 300},
            {"isqueiro", 300, 75},
            {"whisky", 50, 150},
        },
    },
    [11] = {--BAR LV
        ["name"] = "Bar",
        ["position"] = {497.056, -76.041, 998.758, 11, 2},
        ["blip"] = false,
        ["items"] = {
            {"cigarro", 15, 300},
            {"isqueiro", 300, 75},
            {"whisky", 50, 150},
        },
    },
    [12] = {--BAR SF
        ["name"] = "Bar",
        ["position"] = {497.056, -76.041, 998.758, 11, 3},
        ["blip"] = false,
        ["items"] = {
            {"cigarro", 15, 300},
            {"isqueiro", 300, 75},
            {"whisky", 50, 150},
        },
    },
}
drugTime = 90
craft = {
    ["tec9"] = {
        ["item"] =       {0, "ferro", 0, 0, "tec9_corpo", "tec9_boca", 0, "tec9_carregador", 0},
        ["quantidade"] = {0, 1, 0, 0, 1, 1, 0, 1, 0},
        ["take"] = {true, true, true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "Grove",
        ["marker"] = colShape_Grove,
        ["parameters"] = {},
    },
    ["uzi"] = {
        ["item"] =       {0, "ferro", 0, "uzi_boca", "uzi_corpo", 0, 0, "uzi_carregador", 0},
        ["quantidade"] = {0, 2, 0, 1, 1, 0, 0, 1, 0},
        ["take"] = {true, true, true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 120,
        ["acl"] = "Grove",
        ["marker"] = colShape_Grove,
        ["parameters"] = {},
    },
    ["ak"] = {
        ["item"] =       {0, "ferro", 0, "ak_coronha", "ak_corpo", "ak_boca", 0, "ak_carregador", 0},
        ["quantidade"] = {0, 5, 0, 1, 1, 1, 0, 1, 0},
        ["take"] = {true, true, true, true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 180,
        ["acl"] = "Grove",
        ["marker"] = colShape_Grove,
        ["parameters"] = {},
    },
    ["lockpick"] = {
        ["item"] =       {"chave_fenda", "clips", 0, 0, 0, 0, 0, 0, 0},
        ["quantidade"] = {2, 5, 0, 0, 0, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "ALQ",
        ["marker"] = colShape_ALQ,
        ["parameters"] = {},
    },
    ["explosivo"] = {
        ["item"] =       {0, "fios", 0, "celular_desbloqueado", "dinamite", "fita", 0, "polvora", 0},
        ["quantidade"] = {0, 1, 0, 1, 3, 1, 0, 2, 0},
        ["take"] = {true, true, true, true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 120,
        ["acl"] = "ALQ",
        ["marker"] = colShape_ALQ,
        ["parameters"] = {},
    },
    ["colete"] = {
        ["item"] =       {"kevlar", "tecido", 0, 0, 0, 0, 0, 0, 0},
        ["quantidade"] = {2, 3, 0, 0, 0, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 120,
        ["acl"] = "ALQ",
        ["marker"] = colShape_ALQ,
        ["parameters"] = {},
    },
    ["furadeira_adaptada"] = {
        ["item"] =       {"broca", "furadeira", 0, 0, 0, 0, 0, 0, 0},
        ["quantidade"] = {1, 2, 0, 0, 0, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 120,
        ["acl"] = "ALQ",
        ["marker"] = colShape_ALQ,
        ["parameters"] = {},
    },
    ["9mm"] = {
        ["item"] =       {0, "chumbo", 0, 0, "polvora", 0, 0, "capsula_9mm", 0},
        ["quantidade"] = {0, 2, 0, 0, 3, 0, 0, 20, 0},
        ["take"] = {true, true, true},
        ["give"] = 100,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "ALQ",
        ["marker"] = colShape_ALQ,
        ["parameters"] = {},
    },
    [".45"] = {
        ["item"] =       {0, "chumbo", 0, 0, "polvora", 0, 0, "capsula_.45", 0},
        ["quantidade"] = {0, 3, 0, 0, 5, 0, 0, 20, 0},
        ["take"] = {true, true, true},
        ["give"] = 100,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "ALQ",
        ["marker"] = colShape_ALQ,
        ["parameters"] = {},
    },
    ["762"] = {
        ["item"] =       {0, "chumbo", 0, 0, "polvora", 0, 0, "capsula_762", 0},
        ["quantidade"] = {0, 5, 0, 0, 8, 0, 0, 20, 0},
        ["take"] = {true, true, true},
        ["give"] = 100,
        ["trigger"] = false,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "ALQ",
        ["marker"] = colShape_ALQ,
        ["parameters"] = {},
    },
    ["maconha_pe"] = {
        ["item"] =       {0, "fertilizante", 0, 0, "maconha_semente", 0, 0, "vaso", 0},
        ["quantidade"] = {0, 2, 0, 0, 5, 0, 0, 1, 0},
        ["take"] = {true, true, true},
        ["give"] = 1,
        ["trigger"] = "maconha",
        ["tempo"] = 30,
        ["acl"] = "Bloods",
        ["marker"] = colShape_Bloods,
        ["parameters"] = {},
    },
    ["maconha_flor"] = {
        ["item"] =       {0, 0, 0, "maconha_amonia", "maconha_pe", "tesoura", 0, 0, 0},
        ["quantidade"] = {0, 0, 0, 3, 1, 1, 0, 0, 0},
        ["take"] = {true, true, false},
        ["give"] = 30,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "Bloods",
        ["marker"] = colShape_Bloods,
        ["parameters"] = {
            ["chance"] = {1, 3},
            ["msg"] = "A tesoura quebrou durante o processo",
        },
    },
    ["maconha"] = {
        ["item"] =       {0, "maconha_flor", 0, 0, "ziplock", 0, 0, 0, 0},
        ["quantidade"] = {0, 6, 0, 0, 2, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 2,
        ["trigger"] = false,
        ["tempo"] = 5,
        ["acl"] = "Bloods",
        ["marker"] = colShape_Bloods,
        ["parameters"] = {},
    },
    ["cocaina_folha"] = {
        ["item"] =       {0, "fertilizante", 0, 0, "cocaina_semente", 0, 0, "vaso", 0},
        ["quantidade"] = {0, 2, 0, 0, 5, 0, 0, 1, 0},
        ["take"] = {true, true, true},
        ["give"] = 10,
        ["trigger"] = "cocaina",
        ["tempo"] = 30,
        ["acl"] = "Crips",
        ["marker"] = colShape_Crips,
        ["parameters"] = {},
    },
    ["cocaina_po"] = {
        ["item"] =       {0, 0, 0, "cocaina_acido", "cocaina_folha", "peneira", 0, 0, 0},
        ["quantidade"] = {0, 0, 0, 3, 10, 1, 0, 0, 0},
        ["take"] = {true, true, false},
        ["give"] = 30,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "Crips",
        ["marker"] = colShape_Crips,
        ["parameters"] = {
            ["chance"] = {1, 3},
            ["msg"] = "A peneira quebrou durante o processo",
        },
    },
    ["cocaina"] = {
        ["item"] =       {0, "cocaina_po", 0, 0, "ziplock", 0, 0, 0, 0},
        ["quantidade"] = {0, 6, 0, 0, 2, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 2,
        ["trigger"] = false,
        ["tempo"] = 5,
        ["acl"] = "Crips",
        ["marker"] = colShape_Crips,
        ["parameters"] = {},
    },
    ["chip_desbloqueado"] = {
        ["item"] =       {"chip_limitador", "pendrive_malicioso", 0, 0, 0, 0, 0, 0, 0},
        ["quantidade"] = {1, 1, 0, 0, 0, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "MTC",
        ["marker"] = colShape_MTC,
        ["parameters"] = {},
    },
    ["raspberry_malicioso"] = {
        ["item"] =       {"raspberry", "pendrive_malicioso", 0, 0, 0, 0, 0, 0, 0},
        ["quantidade"] = {1, 1, 0, 0, 0, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 120,
        ["acl"] = "ANON",
        ["marker"] = colShape_ANON,
        ["parameters"] = {},
    },
    ["celular_desbloqueado"] = {
        ["item"] =       {"celular", "cartaosd_malicioso", 0, 0, 0, 0, 0, 0, 0},
        ["quantidade"] = {1, 1, 0, 0, 0, 0, 0, 0, 0},
        ["take"] = {true, true},
        ["give"] = 1,
        ["trigger"] = false,
        ["tempo"] = 60,
        ["acl"] = "ANON",
        ["marker"] = colShape_ANON,
        ["parameters"] = {},
    },
}
items = {
    --//////////////////////////////// ALIMENTOS ////////////////////////////////
    --[[
    ["glock"] = {
        ["name"] = "Glock",
        ["type"] = "weapon",
        ["description"] = "Pistola utilizada por cidadões que possuem Porte de Arma.",
        ["weight"] = 1,
        ["usable"] = true,
        ["removable"] = true,
        ["stack"] = false,
        ["durability"] = {
            ["loss"] = 5,
            ["message"] = "Sua Pistola 'Glock' acabou travando por falta de manutenção e uso excessivo",
        },
        ["loss"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["animation"] = "low",
        }
    },
    ["identidade"] = {
        ["name"] = "Identidade",
        ["type"] = "document",
        ["description"] = "Documento de identificação do cidadão.",
        ["weight"] = 0,
        ["usable"] = true,
        ["removable"] = false,
        ["stack"] = false,
        ["durability"] = {
            ["loss"] = 15,
            ["message"] = "Sua 'Identidade' estava muito desgastada e acabou rasgando",
        },
        ["loss"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["valuetype"] = "own_player",
        }
    },
    ["chave_veiculo"] = {
        ["name"] = "Chave de Veículo",
        ["type"] = "document",
        ["description"] = "Chave para trancar e destrancar um veículo específico.",
        ["weight"] = 0,
        ["usable"] = true,
        ["removable"] = true,
        ["stack"] = 1,
        ["durability"] = false,
        ["loss"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["valuetype"] = "vehicle_plate",
        }
    },
    --]]
--------------------------------------------------------------------------------------------------------------------------------
    ["hamburguer"] = {
        ["name"] = "Hambúrguer",
        ["type"] = "food",
        ["description"] = "Alimento rico em calorias, mata sua fome rapidamente.",
        ["weight"] = 0.5,
        ["usable"] = true,
        ["removable"] = true,
        ["stack"] = 5,
        ["durability"] = false,
        ["loss"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 2703,
            ["size"] = 1,
            ["time"] = 14000,
            ["animation"] = {"FOOD", "EAT_Chicken"},
            ["sound"] = "eat",
            ["message"] = "Comendo",
            ["pAttach"] = {"right-wrist", -0.01, 0.05, 0.04, 0, -10, 20},
            ["stats"] = {
                ["food"] = 30,
                ["fat"] = 150
            }
        }
    },
    ["pizza"] = {
        ["name"] = "Pizza",
        ["weight"] = 0.3,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 2702,
            ["size"] = 0.8,
            ["time"] = 14000,
            ["animation"] = {"FOOD", "EAT_Chicken"},
            ["sound"] = "eat",
            ["message"] = "Comendo",
            ["pAttach"] = {"right-wrist", -0.03, 0.06, 0.1, -45, -10, -90},
            ["stats"] = {
                ["food"] = 20,
                ["fat"] = 100
            }
        }
    },
    ["burrito"] = {
        ["name"] = "Burrito",
        ["weight"] = 0.15,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 2769,
            ["size"] = 1,
            ["time"] = 14000,
            ["animation"] = {"FOOD", "EAT_Chicken"},
            ["sound"] = "eat",
            ["message"] = "Comendo",
            ["pAttach"] = {"right-wrist", 0, 0.05, 0.03, 160, 65, 0},
            ["stats"] = {
                ["food"] = 10,
                ["fat"] = 50
            }
        }
    },
    ["leite"] = {
        ["name"] = "Leite",
        ["weight"] = 0.75,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 1484,
            ["size"] = 1,
            ["time"] = 15000,
            ["animation"] = {"VENDING", "VEND_Drink2_P"},
            ["sound"] = "drink",
            ["message"] = "Bebendo",
            ["pAttach"] = {"left-wrist", -0.03, -0.02, 0.05, -15, 200, -70},
            ["stats"] = {
                ["food"] = 30,
                ["drink"] = 30,
                ["fat"] = 150
            }
        }
    },
    ["whisky"] = {
        ["name"] = "Whisky",
        ["weight"] = 0.5,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 1520,
            ["size"] = 1,
            ["time"] = 15000,
            ["animation"] = {"VENDING", "VEND_Drink2_P"},
            ["sound"] = "drink",
            ["message"] = "Bebendo",
            ["pAttach"] = {"left-wrist", -0.22, 0.07, 0.14, 5, 175, 75},
            ["stats"] = {
                ["drink"] = 30
            }
        }
    },
    ["refrigerante"] = {
        ["name"] = "Refrigerante",
        ["weight"] = 0.3,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 2601,
            ["size"] = 0.9,
            ["time"] = 15000,
            ["animation"] = {"VENDING", "VEND_Drink2_P"},
            ["sound"] = "drink",
            ["message"] = "Bebendo",
            ["pAttach"] = {"left-wrist", 0.02, 0.04, 0.11, 0, 0, 90},
            ["stats"] = {
                ["drink"] = 20
            }
        }
    },
    ["suco"] = {
        ["name"] = "Suco de Laranja",
        ["weight"] = 0.15,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 1544,
            ["size"] = 1,
            ["time"] = 15000,
            ["animation"] = {"VENDING", "VEND_Drink2_P"},
            ["sound"] = "drink",
            ["message"] = "Bebendo",
            ["pAttach"] = {"left-wrist", -0.26, 0.06, 0.15, 195, 0, -130},
            ["stats"] = {
                ["drink"] = 10
            }
        }
    },
    ["cafe"] = {
        ["name"] = "Café Expresso",
        ["weight"] = 0.5,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 1546,
            ["size"] = 1,
            ["time"] = 15000,
            ["animation"] = {"VENDING", "VEND_Drink2_P"},
            ["sound"] = "drink",
            ["message"] = "Bebendo",
            ["pAttach"] = {"left-wrist", -3.4694469519536e-18, 0.08, 0.1, 185, 5, -120},
            ["stats"] = {
                ["energy"] = 15
            }
        }
    },
    ["energetico"] = {
        ["name"] = "Energético",
        ["weight"] = 0.5,
        ["type"] = "food",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 1455,
            ["size"] = 1.1,
            ["time"] = 15000,
            ["animation"] = {"VENDING", "VEND_Drink2_P"},
            ["sound"] = "drink",
            ["message"] = "Bebendo",
            ["pAttach"] = {"left-wrist", -0.02, 0.11, 0.12, 20, 190, 60},
            ["stats"] = {
                ["energy"] = 30,
                ["speed"] = true
            }
        }
    },
    --//////////////////////////////// ARMAMENTOS ////////////////////////////////
    ["ak"] = {
        ["name"] = "AK-47",
        ["weight"] = 4,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["animation"] = "high",
        }
    },
    ["m4"] = {
        ["name"] = "M4A4",
        ["weight"] = 4,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["animation"] = "high",
        }
    },
    ["uzi"] = {
        ["name"] = "Micro UZI",
        ["weight"] = 2.5,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["animation"] = "high",
        }
    },
    ["ump"] = {
        ["name"] = "UMP-45",
        ["weight"] = 2.5,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["animation"] = "high",
        }
    },
    ["escopeta"] = {
        ["name"] = "Escopeta",
        ["weight"] = 3,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 25,
            ["slot"] = 3,
            ["ammo"] = "12",
            ["animation"] = "high",
        }
    },
    ["p2000"] = {
        ["name"] = "P2000",
        ["weight"] = 1,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["animation"] = "low",
        }
    },
    ["tec9"] = {
        ["name"] = "TEC-9",
        ["weight"] = 1,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["animation"] = "low",
        }
    },
    ["glock"] = {
        ["name"] = "Glock",
        ["weight"] = 1,
        ["type"] = "weapon",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["animation"] = "low",
        }
    },
    --//////////////////////////////// ARMAS BRANCAS ////////////////////////////////
    ["cassetete"] = {
        ["name"] = "Cassetete",
        ["weight"] = 0.5,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 3,
            ["slot"] = 1,
            ["qntd"] = 1,
        }
    },
    ["cutelo"] = {
        ["name"] = "Cutelo",
        ["weight"] = 1,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 8,
            ["slot"] = 1,
            ["qntd"] = 1,
        }
    },
    ["dildo"] = {
        ["name"] = "Dildo",
        ["weight"] = 1,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 10,
            ["slot"] = 10,
            ["qntd"] = 1,
        }
    },
    ["facao"] = {
        ["name"] = "Facão",
        ["weight"] = 1,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 4,
            ["slot"] = 1,
            ["qntd"] = 1,
        }
    },
    ["gas"] = {
        ["name"] = "Gás Lacrimogêneo",
        ["weight"] = 0.3,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 17,
            ["slot"] = 8,
            ["qntd"] = 5,
        }
    },
    ["paraquedas"] = {
        ["name"] = "Paraquedas",
        ["weight"] = 2,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 46,
            ["slot"] = 11,
            ["qntd"] = 1,
        }
    },
    ["picareta"] = {
        ["name"] = "Picareta",
        ["weight"] = 1,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 2,
            ["slot"] = 1,
            ["qntd"] = 1,
        }
    },
    ["spray_pimenta"] = {
        ["name"] = "Spray de Pimenta",
        ["weight"] = 0.3,
        ["type"] = "weapon2",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
        ["parameters"] = {
            ["id"] = 41,
            ["slot"] = 9,
            ["qntd"] = 500,
        }
    },
    --//////////////////////////////// MUNIÇÕES ////////////////////////////////
    ["762"] = {
        ["name"] = "Munição .762",
        ["weight"] = 0.03,
        ["type"] = "ammo",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["556"] = {
        ["name"] = "Munição .556",
        ["weight"] = 0.03,
        ["type"] = "ammo",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    [".45"] = {
        ["name"] = "Munição .45 ACP",
        ["weight"] = 0.02,
        ["type"] = "ammo",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["12"] = {
        ["name"] = "Bala de Borracha",
        ["weight"] = 0.02,
        ["type"] = "ammo",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["9mm"] = {
        ["name"] = "Munição 9mm",
        ["weight"] = 0.01,
        ["type"] = "ammo",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    --//////////////////////////////// PARTES DE FABRICAÇÃO ////////////////////////////////
    ["abracadeira"] = {
        ["name"] = "Abraçadeira Plástica",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["broca"] = {
        ["name"] = "Broca Industrial",
        ["weight"] = 0.5,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["cartaosd"] = {
        ["name"] = "Cartão Micro-SD",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["chave_fenda"] = {
        ["name"] = "Chave de Fenda",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["chip_limitador"] = {
        ["name"] = "Chip Limitador",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["clips"] = {
        ["name"] = "Clips",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["dinamite"] = {
        ["name"] = "Banana de Dinamite",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["fios"] = {
        ["name"] = "Fios de Cobre",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["furadeira"] = {
        ["name"] = "Furadeira",
        ["weight"] = 0.75,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["lubrificante"] = {
        ["name"] = "Óleo Lubrificante",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["pendrive"] = {
        ["name"] = "Pen-Drive",
        ["weight"] = 0.05,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["polvora"] = {
        ["name"] = "Pólvora",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["raspberry"] = {
        ["name"] = "Raspberry",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["tecido"] = {
        ["name"] = "Tecido",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["kevlar"] = {
        ["name"] = "Kevlar",
        ["weight"] = 1.5,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["peneira"] = {
        ["name"] = "Peneira",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["tesoura"] = {
        ["name"] = "Tesoura",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["ziplock"] = {
        ["name"] = "Embalagem Plástica",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["fertilizante"] = {
        ["name"] = "Fertilizante",
        ["weight"] = 0.3,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["cocaina_folha"] = {
        ["name"] = "Folha de Coca",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["cocaina_semente"] = {
        ["name"] = "Semente de Coca",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["cocaina_po"] = {
        ["name"] = "Pó de Cocaína",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["cocaina_acido"] = {
        ["name"] = "Ácido Sulfúrico",
        ["weight"] = 0.3,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["maconha_semente"] = {
        ["name"] = "Semente de Maconha",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["maconha_pe"] = {
        ["name"] = "Pé de Maconha",
        ["weight"] = 0.5,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["maconha_amonia"] = {
        ["name"] = "Hidróxido de Amônia",
        ["weight"] = 0.3,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["maconha_flor"] = {
        ["name"] = "Bud de Maconha",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["ak_boca"] = {
        ["name"] = "Bocal de AK-47",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["ak_carregador"] = {
        ["name"] = "Carregador de AK-47",
        ["weight"] = 0.5,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["ak_coronha"] = {
        ["name"] = "Coronha de AK-47",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["ak_corpo"] = {
        ["name"] = "Corpo de AK-47",
        ["weight"] = 3,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["uzi_boca"] = {
        ["name"] = "Bocal de Micro-UZI",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["uzi_carregador"] = {
        ["name"] = "Carregador de Micro-UZI",
        ["weight"] = 0.35,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["uzi_corpo"] = {
        ["name"] = "Corpo de Micro-UZI",
        ["weight"] = 1.5,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["tec9_boca"] = {
        ["name"] = "Bocal de TEC-9",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["tec9_carregador"] = {
        ["name"] = "Carregador de TEC-9",
        ["weight"] = 0.3,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["tec9_corpo"] = {
        ["name"] = "Corpo de TEC-9",
        ["weight"] = 0.5,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["capsula_9mm"] = {
        ["name"] = "Cápsula de 9mm",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["capsula_.45"] = {
        ["name"] = "Cápsula de .45 ACP",
        ["weight"] = 0.02,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["capsula_762"] = {
        ["name"] = "Cápsula de .762",
        ["weight"] = 0.03,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    --//////////////////////////////// ILEGAIS ////////////////////////////////
    ["cocaina"] = {
        ["name"] = "Cocaína",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["maconha"] = {
        ["name"] = "Maconha",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["dinheiro_sujo"] = {
        ["name"] = "Dinheiro Sujo",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["explosivo"] = {
        ["name"] = "Explosivo C4",
        ["weight"] = 1.5,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["fita"] = {
        ["name"] = "Fita Adesiva",
        ["weight"] = 0.05,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["furadeira_adaptada"] = {
        ["name"] = "Furadeira Adaptada",
        ["weight"] = 3,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["lockpick"] = {
        ["name"] = "Lockpick",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["pecas_carro"] = {
        ["name"] = "Peças de Veículos",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["pendrive_info"] = {
        ["name"] = "Pendrive [Informações]",
        ["weight"] = 0.05,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["pendrive_malicioso"] = {
        ["name"] = "Pendrive [Malicioso]",
        ["weight"] = 0.05,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["cartaosd_malicioso"] = {
        ["name"] = "Cartão SD [Malicioso]",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["raspberry_malicioso"] = {
        ["name"] = "Raspberry [Malicioso]",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["chip_desbloqueado"] = {
        ["name"] = "Chip [Desbloqueado]",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["celular_desbloqueado"] = {
        ["name"] = "Celular [Desbloqueado]",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    --//////////////////////////////// UTILITÁRIOS ////////////////////////////////
    ["analgesico"] = {--recupera vida aos poucos
        ["name"] = "Analgésico",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["bandagem"] = {
        ["name"] = "Bandagem",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["function"] = function(playerSource)
            local health = getElementHealth(playerSource)
            if health < 100 then
                takeItem(playerSource, "bandagem", 1)
                exports.progress:showProgress(playerSource, 10)
                setElementFrozen(playerSource, true)
                toggleAllControls(playerSource, false)
                setAnimation(playerSource, "BOMBER", "BOM_Plant_Loop", 10000, true)
                setTimer(function()
                    setElementHealth(playerSource, health + 20)
                    setElementFrozen(playerSource, false)
                    toggleAllControls(playerSource, true)
                end, 10000, 1)
            else
                exports.infobox:addNotification(playerSource, "Você não precisa se curar", "error")
            end
        end
    },
    ["capacete"] = {
        ["name"] = "Capacete",
        ["weight"] = 1,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["cigarro"] = {
        ["name"] = "Cigarro",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["colete"] = {
        ["name"] = "Colete Balístico",
        ["weight"] = 3,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["dado"] = {
        ["name"] = "Dado",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["function"] = function(playerSource)
            local random = math.random(1, 5)
            if random == 1 then
                takeItem(playerSource, "dado", 1)
                exports.infobox:addNotification(playerSource, "O dado caiu muito longe e você o perdeu", "warning")
            else
                local x, y, z = getElementPosition(playerSource)
                local data = getElementData(playerSource, "player:infos") or {}
                local name = data["name"] or getPlayerName(playerSource)
                local id = data["id"] or "N/A"
                local random2 = math.random(1, 6)
                for _, players in pairs(getElementsWithinRange(x, y, z, 10, "player")) do
                    exports.infobox:addNotification(players, "'"..name.." #"..id.."' jogou o dado e caiu no número: "..random2, "info")
                end
            end
        end
    },
    ["jbl"] = {
        ["name"] = "JBL",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["mascara"] = {
        ["name"] = "Máscara Palhaço",
        ["weight"] = 0.05,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["moeda"] = {
        ["name"] = "Moeda",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["function"] = function(playerSource)
            local random = math.random(1, 5)
            if random == 1 then
                takeItem(playerSource, "moeda", 1)
                exports.infobox:addNotification(playerSource, "A moeda caiu muito longe e você a perdeu", "warning")
            else
                local x, y, z = getElementPosition(playerSource)
                local data = getElementData(playerSource, "player:infos") or {}
                local name = data["name"] or getPlayerName(playerSource)
                local id = data["id"] or "N/A"
                local random2 = math.random(1, 2)
                local tabela = {[1] = "'CARA'", [2] = "'COROA'"}
                for _, players in pairs(getElementsWithinRange(x, y, z, 10, "player")) do
                    exports.infobox:addNotification(players, "'"..name.." #"..id.."' jogou a moeda e caiu: "..tabela[random2], "info")
                end
            end
        end
    },
    ["presente"] = {
        ["name"] = "Presente VIP",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["radinho"] = {
        ["name"] = "Rádio Comunicador",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    --//////////////////////////////// SEM AÇÃO ////////////////////////////////
    ["algema"] = {
        ["name"] = "Algema",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = true,
    },
    ["bronze"] = {
        ["name"] = "Minério de Bronze",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["camisinha"] = {
        ["name"] = "Preservativo",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["cartao"] = {
        ["name"] = "Cartão de Débito",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["celular"] = {
        ["name"] = "Celular",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["chumbo"] = {
        ["name"] = "Minério de Chumbo",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["diamante"] = {
        ["name"] = "Minério de Diamante",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["ferro"] = {
        ["name"] = "Minério de Ferro",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["garrafa"] = {
        ["name"] = "Garrafa Vazia",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["gasolina"] = {
        ["name"] = "Galão de Gasolina",
        ["weight"] = 3,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["kit_reparo"] = {
        ["name"] = "Kit de Reparo",
        ["weight"] = 5,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = {}
    },
    ["isqueiro"] = {
        ["name"] = "Isqueiro",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["maquininha"] = {
        ["name"] = "Máquina de Cartão",
        ["weight"] = 1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["mochila_p"] = {
        ["name"] = "Mochila Pequena",
        ["weight"] = 0.5,
        ["type"] = "bag",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = 20,
    },
    ["mochila_m"] = {
        ["name"] = "Mochila Média",
        ["weight"] = 0.5,
        ["type"] = "bag",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = 30,
    },
    ["mochila_g"] = {
        ["name"] = "Mochila Grande",
        ["weight"] = 0.5,
        ["type"] = "bag",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
        ["parameters"] = 50,
    },
    ["ouro"] = {
        ["name"] = "Minério de Ouro",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["prata"] = {
        ["name"] = "Minério de Prata",
        ["weight"] = 0.1,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["reparo_funilaria"] = {
        ["name"] = "Reparo Funilaria",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["reparo_motor"] = {
        ["name"] = "Reparo Motor",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["reparo_pneu"] = {
        ["name"] = "Reparo Pneus",
        ["weight"] = 0.2,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["ticket"] = {
        ["name"] = "Ticket de Corrida",
        ["weight"] = 0.01,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["vaso"] = {
        ["name"] = "Vaso de Planta",
        ["weight"] = 0.15,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    --//////////////////////////////// DOCUMENTOS ////////////////////////////////
    ["chave_casa"] = {
        ["name"] = "Chave de Casa",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["chave_veiculo"] = {
        ["name"] = "Chave de Veículo",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["distintivo"] = {
        ["name"] = "Distintivo Policial",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = true,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
        ["function"] = function(playerSource)
            local x, y, z = getElementPosition(playerSource)
            local data = getElementData(playerSource, "player:infos") or {}
            local name = data["name"] or getPlayerName(playerSource)
            local id = data["id"] or "N/A"
            local group = data["group"] or "N/A"
            local inRange = getElementsWithinRange(x, y, z, 3, "player")
            if (#inRange) > 1 then
                for _, players in pairs(inRange) do
                    if players ~= playerSource then
                        exports.infobox:addNotification(players, "'"..name.." #"..id.."' está lhe mostrando seu distintivo da corporação '"..group.."'", "info")
                    else
                        exports.infobox:addNotification(playerSource, "Você mostrou seu distintivo para as pessoas próximas", "success")
                    end
                end
            else
                exports.infobox:addNotification(playerSource, "Não há ninguém próximo para você mostrar seu distintivo", "error")
            end
        end
    },
    ["identidade"] = {
        ["name"] = "Identidade",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["habilitacao"] = {
        ["name"] = "Habilitação",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["licenciamento"] = {
        ["name"] = "Licenciamento Veicular",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["porte"] = {
        ["name"] = "Porte de Arma",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    ["trabalho"] = {
        ["name"] = "Carteira de Trabalho",
        ["weight"] = 0,
        ["type"] = "object",
        ["usable"] = false,
        ["tradable"] = false,
        ["dropable"] = false,
        ["deadly"] = true,
        ["illegal"] = false,
    },
    --//////////////////////////////// SKINS ////////////////////////////////
    ["ak_wastelandrebel"] = {
        ["name"] = "AK-47 [Wasteland Rebel]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 4,
        }
    },
    ["ak_vulcan"] = {
        ["name"] = "AK-47 [Vulcan]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 2,
        }
    },
    ["ak_theempress"] = {
        ["name"] = "AK-47 [The Empress]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 3,
        }
    },
    ["ak_neva"] = {
        ["name"] = "AK-47 [Neva]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 3,
        }
    },
    ["ak_hyperbeast"] = {
        ["name"] = "AK-47 [Hyper Beast]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 2,
        }
    },
    ["ak_dragonlore"] = {
        ["name"] = "AK-47 [Dragon Lore]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 5,
        }
    },
    ["ak_bluewolf"] = {
        ["name"] = "AK-47 [Blue Wolf]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 3,
        }
    },
    ["ak_asiimov"] = {
        ["name"] = "AK-47 [Asiimov]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 1,
        }
    },
    ["ak_aquamarine"] = {
        ["name"] = "AK-47 [Aquamarine]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 30,
            ["slot"] = 5,
            ["ammo"] = "762",
            ["item"] = "ak",
            ["texture"] = "ak47",
            ["rarity"] = 4,
        }
    },
    ["glock_wolf"] = {
        ["name"] = "Glock [Wolf]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "glock",
            ["texture"] = "pist_glo"
        }
    },
    ["glock_weasel"] = {
        ["name"] = "Glock [Weasel]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "glock",
            ["texture"] = "pist_glo"
        }
    },
    ["glock_waterelemental"] = {
        ["name"] = "Glock [Water Elemental]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "glock",
            ["texture"] = "pist_glo"
        }
    },
    ["glock_wastelandrebel"] = {
        ["name"] = "Glock [Wasteland Rebel]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "glock",
            ["texture"] = "pist_glo"
        }
    },
    ["glock_toxictsunami"] = {
        ["name"] = "Glock [Toxic Tsunami]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "glock",
            ["texture"] = "pist_glo"
        }
    },
    ["glock_rise"] = {
        ["name"] = "Glock [Rise]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "glock",
            ["texture"] = "pist_glo"
        }
    },
    ["glock_fade"] = {
        ["name"] = "Glock [Fade]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 24,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "glock",
            ["texture"] = "pist_glo"
        }
    },
    ["m4_urbanddpat"] = {
        ["name"] = "M4A4 [Urban DDPAT]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_spacedeath"] = {
        ["name"] = "M4A4 [Space Death]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_poseidon"] = {
        ["name"] = "M4A4 [Poseidon]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_killconfirmed"] = {
        ["name"] = "M4A4 [Kill Confirmed]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_hyperbeast"] = {
        ["name"] = "M4A4 [Hyper Beast]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_howl"] = {
        ["name"] = "M4A4 [Howl]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_hellfire"] = {
        ["name"] = "M4A4 [Hellfire]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_desolatespace"] = {
        ["name"] = "M4A4 [Desolate Space]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["m4_asiimov"] = {
        ["name"] = "M4A4 [Asiimov]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 31,
            ["slot"] = 5,
            ["ammo"] = "556",
            ["item"] = "m4",
            ["texture"] = "gun_m4"
        }
    },
    ["uzi_wastelandrebel"] = {
        ["name"] = "Micro UZI [Wasteland Rebel]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "uzi",
            ["texture"] = "mac10"
        }
    },
    ["uzi_ultrawhite"] = {
        ["name"] = "Micro UZI [Ultra White]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "uzi",
            ["texture"] = "mac10"
        }
    },
    ["uzi_ultrapink"] = {
        ["name"] = "Micro UZI [Ultra Pink]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "uzi",
            ["texture"] = "mac10"
        }
    },
    ["uzi_rider"] = {
        ["name"] = "Micro UZI [Rider]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "uzi",
            ["texture"] = "mac10"
        }
    },
    ["uzi_redhot"] = {
        ["name"] = "Micro UZI [Red Hot]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "uzi",
            ["texture"] = "mac10"
        }
    },
    ["uzi_psychopath"] = {
        ["name"] = "Micro UZI [Psychopath]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "uzi",
            ["texture"] = "mac10"
        }
    },
    ["uzi_fade"] = {
        ["name"] = "Micro UZI [Fade]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 28,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "uzi",
            ["texture"] = "mac10"
        }
    },
    ["p2000_deadman"] = {
        ["name"] = "P2000 [Dead Man]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "p2000",
            ["texture"] = "TexturasTurga"
        }
    },
    ["p2000_fireelemental"] = {
        ["name"] = "P2000 [Fire Elemental]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "p2000",
            ["texture"] = "TexturasTurga"
        }
    },
    ["p2000_handgun"] = {
        ["name"] = "P2000 [Handgun]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "p2000",
            ["texture"] = "TexturasTurga"
        }
    },
    ["p2000_imperialdragon"] = {
        ["name"] = "P2000 [Imperial Dragon]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "p2000",
            ["texture"] = "TexturasTurga"
        }
    },
    ["p2000_impire"] = {
        ["name"] = "P2000 [Impire]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "p2000",
            ["texture"] = "TexturasTurga"
        }
    },
    ["p2000_neural"] = {
        ["name"] = "P2000 [Neural]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "p2000",
            ["texture"] = "TexturasTurga"
        }
    },
    ["p2000_renegade"] = {
        ["name"] = "P2000 [Renegade]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 23,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "p2000",
            ["texture"] = "TexturasTurga"
        }
    },
    ["tec9_toxic"] = {
        ["name"] = "TEC-9 [Toxic]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["tec9_titaniumbit"] = {
        ["name"] = "TEC-9 [Titanium Bit]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["tec9_reentry"] = {
        ["name"] = "TEC-9 [Re-Entry]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["tec9_osmotr"] = {
        ["name"] = "TEC-9 [Osmotr]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["tec9_isaac"] = {
        ["name"] = "TEC-9 [Isaac]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["tec9_galaxy"] = {
        ["name"] = "TEC-9 [Galaxy]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["tec9_fuelinjector"] = {
        ["name"] = "TEC-9 [Fuel Injector]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["tec9_avalanche"] = {
        ["name"] = "TEC-9 [Avalanche]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 22,
            ["slot"] = 2,
            ["ammo"] = "9mm",
            ["item"] = "tec9",
            ["texture"] = "pist_tec9"
        }
    },
    ["ump_witsend"] = {
        ["name"] = "UMP-45 [Witsend]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "ump",
            ["texture"] = "ump45"
        }
    },
    ["ump_vertex"] = {
        ["name"] = "UMP-45 [Vertex]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "ump",
            ["texture"] = "ump45"
        }
    },
    ["ump_scaffold"] = {
        ["name"] = "UMP-45 [Scaffold]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "ump",
            ["texture"] = "ump45"
        }
    },
    ["ump_riot"] = {
        ["name"] = "UMP-45 [Riot]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "ump",
            ["texture"] = "ump45"
        }
    },
    ["ump_primalsaber"] = {
        ["name"] = "UMP-45 [Primal Saber]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "ump",
            ["texture"] = "ump45"
        }
    },
    ["ump_grandprix"] = {
        ["name"] = "UMP-45 [Grand Prix]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "ump",
            ["texture"] = "ump45"
        }
    },
    ["ump_blaze"] = {
        ["name"] = "UMP-45 [Blaze]",
        ["weight"] = 0,
        ["type"] = "skin",
        ["usable"] = true,
        ["tradable"] = true,
        ["dropable"] = true,
        ["deadly"] = false,
        ["illegal"] = false,
        ["parameters"] = {
            ["id"] = 29,
            ["slot"] = 4,
            ["ammo"] = ".45",
            ["item"] = "ump",
            ["texture"] = "ump45"
        }
    },
}
rarity_colors = {
    [1] = tocolor(15, 145, 0, 255),
    [2] = tocolor(90, 95, 200, 255),
    [3] = tocolor(150, 0, 0, 255),
    [4] = tocolor(110, 0, 170, 255),
    [5] = tocolor(230, 145, 15, 255),
}
positions = {
    inventory1 = {
        [1] =  {2, 42},
        [2] =  {94, 42},
        [3] =  {186, 42},
        [4] =  {278, 42},
        [5] =  {370, 42},
        [6] =  {2, 134},
        [7] =  {94, 134},
        [8] =  {186, 134},
        [9] =  {278, 134},
        [10] = {370, 134},
        [11] = {2, 226},
        [12] = {94, 226},
        [13] = {186, 226},
        [14] = {278, 226},
        [15] = {370, 226},
        [16] = {2, 318},
        [17] = {94, 318},
        [18] = {186, 318},
        [19] = {278, 318},
        [20] = {370, 318},
        [21] = {2, 410},
        [22] = {94, 410},
        [23] = {186, 410},
        [24] = {278, 410},
        [25] = {370, 410},
        [26] = {2, 502},
        [27] = {94, 502},
        [28] = {186, 502},
        [29] = {278, 502},
        [30] = {370, 502},
    },
    inventory2 = {
        [1] =  {619, 42},
        [2] =  {711, 42},
        [3] =  {803, 42},
        [4] =  {895, 42},
        [5] =  {987, 42},
        [6] =  {619, 134},
        [7] =  {711, 134},
        [8] =  {803, 134},
        [9] =  {895, 134},
        [10] = {987, 134},
        [11] = {619, 226},
        [12] = {711, 226},
        [13] = {803, 226},
        [14] = {895, 226},
        [15] = {987, 226},
        [16] = {619, 318},
        [17] = {711, 318},
        [18] = {803, 318},
        [19] = {895, 318},
        [20] = {987, 318},
        [21] = {619, 410},
        [22] = {711, 410},
        [23] = {803, 410},
        [24] = {895, 410},
        [25] = {987, 410},
        [26] = {619, 502},
        [27] = {711, 502},
        [28] = {803, 502},
        [29] = {895, 502},
        [30] = {987, 502},
    },
    actions = {
        [1] = {147, "use"},
        [2] = {267, "trade"},
        [3] = {387, "craft"},
    },
    hotbar = {
        [1] = 0,
        [2] = 100,
        [3] = 200,
        [4] = 300,
        [5] = 400,
    },
}
craftPositions = {
    [1] = {0.5490, 0.2891, 0.5966, 0.3789, 0.6149, 0.4049},
    [2] = {0.6179, 0.2891, 0.6654, 0.3789, 0.6837, 0.4049},
    [3] = {0.6867, 0.2891, 0.7343, 0.3789, 0.7526, 0.4049},
    [4] = {0.5490, 0.4115, 0.5966, 0.5026, 0.6149, 0.5286},
    [5] = {0.6179, 0.4115, 0.6654, 0.5026, 0.6837, 0.5286},
    [6] = {0.6867, 0.4115, 0.7343, 0.5026, 0.7526, 0.5286},
    [7] = {0.5490, 0.5339, 0.5966, 0.6250, 0.6149, 0.6510},
    [8] = {0.6179, 0.5339, 0.6654, 0.6250, 0.6837, 0.6510},
    [9] = {0.6867, 0.5339, 0.7343, 0.6250, 0.7526, 0.6510},
    [10] = {0.7555, 0.4115, 0.8031, 0.5026, 0.8214, 0.5286},
}
shotOneBullet = {
    [0] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [8] = true,
    [17] = true,
    [41] = true,
    [46] = true,
}